# Generated by Django 6.0.4 on 2026-04-27 17:46

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_size_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='hex_code',
            field=colorfield.fields.ColorField(blank=True, default='#000000', image_field=None, max_length=7, samples=None),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
